version: '3.1'
services:  
  db:
    image: mysql
    volumes:
      - ./.data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: vestas
      MYSQL_USER: vestas
      MYSQL_PASSWORD: vestas
    ports:
      - 3306:3306
  api:
    image: mcr.microsoft.com\dotnet\sdk:5.0