version: '3.1'
services:  
  vestas-db:
    image: mysql
    volumes:
      - ./.data/db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: vestas
      MYSQL_USER: vestas
      MYSQL_PASSWORD: vestas
    ports:
      - 3306:3306
  # vestas-api:
  #   build:
  #     dockerfile: ./
  #   depends_on:
  #     - db
  #   ports:
  #     - 5000:80
  #   command: dotnet Vestas.Test.Delivery.dll