// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vestas.Test.Delivery.Infra;

namespace Vestas.Test.Delivery.Infra.Migrations
{
    [DbContext(typeof(DeliveryPointContext))]
    partial class DeliveryPointContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.14");

            modelBuilder.Entity("Vestas.Test.Delivery.Infra.Entity.DeliveryPointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Cost")
                        .HasColumnType("INTEGER");

                    b.Property<char>("Destination")
                        .HasColumnType("TEXT");

                    b.Property<char>("Origin")
                        .HasColumnType("TEXT");

                    b.Property<int>("Time")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("DeliveryPoint");
                });
#pragma warning restore 612, 618
        }
    }
}
